apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  block-aaaa.override: |
    template IN AAAA . {
        rcode NOERROR
        answer "{{ .Name }} 0 IN SOA ns.dns.cluster.local. hostmaster.cluster.local. 0 60 60 60 0"
    }
